tasks:
  # Get:
  - source: tasks.raw.get_births
    params:
      raw_births_file: '{{dataset_nacimientos_path}}'
    product:
      data: _products/raw/births.parquet
    on_finish: tests.raw.test_births_clean

  - source: tasks.raw.get_stillbirths
    params:
      raw_stillbirths_file: '{{dataset_mortinatos_path}}'
      deceases_codes: '{{deceases_codes}}'      
    product: 
      data: _products/raw/stillbirths.parquet
    on_finish: tests.raw.test_stillbirths_clean

  - source: tasks.raw.get_percentage_for_each_cause
    name: raw__get_percentage_for_each_cause
    params:
      raw_stillbirths_file: '{{dataset_mortinatos_path}}'
      deceases_codes: '{{deceases_codes}}'      
    product: _products/raw/percentage-causes.parquet

  # Aggr:
  - source: tasks.aggr.get_percentages_for_each_code_group
    name: aggr__get_percentages_for_each_code_group
    product: _products/aggr/percentage-causes-aggr.parquet

  # Process
  - source: tasks.rates.get_annual
    params:
      rates_over: '{{rates_people_param}}'
    product:
      data: _products/rates/rates-by-year.parquet

  - source: tasks.rates.get_quinquenial
    name: rates__get_quinquenial
    params:
      rates_over: '{{rates_people_param}}'
    product: 
      data: _products/rates/rates-by-quinquenios.parquet

  # Clustering process
  - source: tasks.spatial_processing.get_quinquennial_labels
    name: spatial_processing__get_quinquennial_labels
    product: 
      cluster_labels: _products/spatial_processing/etiquetas-cluster-por-quinquenios.parquet
      moran_results: _products/spatial_processing/moran-por-quinquenios.parquet

  - source: tasks.spatial_processing.get_lisa_labels_for_each_decease_code
    name: spatial_processing__get_lisa_labels_for_each_decease_code
    product: 
      cluster_labels: _products/spatial_processing/codigos-etiquetas-cluster-por-quinquenios.parquet
      moran_results: _products/spatial_processing/codigos-moran-por-quinquenios.parquet

  - source: tasks.clustermaps.get_quinquennial
    name: clustermap_quinquennial
    product: _products/clustermaps/tasas-clustermap-quinquenal.png

  - source: tasks.clustermaps.get_quinquennial_for_codes
    name: clustermap__quinquennial_for_codes
    product: _products/clustermaps/por-codigo/

  # Figures:
  - source: tasks.maps.by_years
    name: maps_by_years
    product: _products/maps/maps-by-years.png

  - source: tasks.maps.by_quinquenios
    name: maps_by_quinquenios
    product: _products/maps/maps-by-quinquenios.png

  - source: tasks.maps.get_code_percentages_quinquenios
    name: maps__code_percentages_quinquenios
    product: _products/maps/por-codigo/

  - source: tasks.lineplots.by_years
    name: lineplots_by_years
    product: _products/lineplots/anuales

  - source: tasks.lineplots.by_quinquennios
    name: lineplots_by_quinquennios
    product: _products/lineplots/quinquenales

  - source: tasks.tables.by_years
    name: tables_by_years
    product: _products/tables/anuales

  # Report:
  - source: tasks.report.create_annual
    name: create_annual_report
    params:
      rates_param: '{{rates_people_param}}'
    product: _output/reporte_anual.pdf

  - source: tasks.report.create_quinquennal
    name: create_quinquennal_report
    params:
      rates_param: '{{rates_people_param}}'
    product: _output/reporte_quinquenal.pdf

