tasks:
  # Get:
  - source: tasks.raw.get_births
    params:
      input_file: '{{dataset_nacimientos_path}}'
    product:
      data: _products/raw/births.parquet

  - source: tasks.raw.get_stillbirths
    params:
      input_file: '{{dataset_mortinatos_path}}'
    product: 
      data: _products/raw/stillbirths.parquet

  # Process
  - source: tasks.rates.get_annual
    product:
      data: _products/rates/rates-by-year.parquet

  - source: tasks.rates.get_quinquenial
    product: 
      data: _products/rates/rates-by-quinquenios.parquet

  # Plot
  - source: scripts/plot-births.py
    product:
      nb: _output/plot-births.ipynb
      data: _output/plot-births.pdf

  - source: scripts/plot-stillbirths.py
    product:
      nb: _output/plot-stillbirths.ipynb
      data: _output/plot-stillbirths.pdf

  - source: scripts/plot-rates-years.py
    product:
      nb: _output/plot-rates-years.ipynb
      data: _output/plot-rates-years.pdf

  - source: scripts/plot-rates-quinquenios.py
    product:
      nb: _output/plot-rates-quinquenios.ipynb
      data: _output/plot-rates-quinquenios.pdf
      
  # Data profiling:
  #- source: scripts/profile-annual-rates.py
  #  product:
  #    nb: _output/profile-annual-rates.ipynb